# Generated by Django 5.2 on 2025-04-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
